### ISSUE TITLE
Is weak error 'W' supported?

### ISSUE THREAD

**Issue by Paebbels** [ktbarrett/hdltypes#21]
According to #3, a 9-valued logic as proposed by IEEE Std. 1164 was used for designing the logic type.

But in README, only an 8-valued logic is explained:
> Can represent `0`, `1`, high impedance (`Z`), weak values (`L` and `H`), or indeterminate values (`X`, `U`, and `-`) that can occur in hardware.

Is `W` (weak error) supported?

-----------------
For correctness:
* `X` is strong error and belongs to the strong values `0` and `1`
* Values like `U` and `-` are called meta values

**Comment by ktbarrett** [comment]
Yes, `W` is supported, see [here](https://hdltypes.readthedocs.io/en/latest/?badge=latest#_CPPv4N8hdltypes5Logic10value_type1WE). I will also update the README.

Thanks for showing interest in the project. It still has a lot of work left... This project was motivated by a similar project I've done at work, which included only fixed point datatypes, following a lack of enthusiasm for modelling with SystemC.
